# Netdata exporting — remote_write в VictoriaMetrics
# Документация: https://learn.netdata.cloud/docs/exporting-metrics/prometheus-remote-write
#
# Netdata в host network → VictoriaMetrics слушает на порту 8428 → localhost:8428 доступен

[exporting:global]
    enabled = yes

[prometheus_remote_write:victoriametrics]
    enabled = yes
    destination = localhost:8428
    remote write URL path = /api/v1/write
    update every = 10
    send names instead of ids = yes
    send configured labels = yes
