"""
Response schemas для Image generation endpoints.

Содержит Pydantic модели для:
- Статус системы генерации изображений
- Очередь генерации
- Статистика пользователя
- Информация об API провайдере

Version: Phase 1.2 Type Safety (2025-11-29)
"""

from pydantic import BaseModel, Field
from typing import Dict, List, Optional
from uuid import UUID


class QueueStats(BaseModel):
    """
    Статистика очереди генерации изображений.

    Используется в ImageGenerationStatusResponse.

    Attributes:
        pending_tasks: Задачи в очереди ожидания
        processing_tasks: Задачи в процессе выполнения
        completed_today: Выполнено задач сегодня
        failed_today: Провалено задач сегодня
    """

    pending_tasks: int = Field(ge=0, description="Tasks waiting in queue")
    processing_tasks: int = Field(ge=0, description="Currently processing")
    completed_today: int = Field(ge=0, description="Completed today")
    failed_today: int = Field(ge=0, description="Failed today")


class UserGenerationInfo(BaseModel):
    """
    Информация о квоте генерации для пользователя.

    Используется в ImageGenerationStatusResponse.

    Attributes:
        id: UUID пользователя
        can_generate: Может ли генерировать изображения сейчас
        remaining_quota: Оставшаяся квота на месяц (None = unlimited)
    """

    id: UUID
    can_generate: bool = Field(description="Can generate images now")
    remaining_quota: Optional[int] = Field(
        None, ge=0, description="Remaining quota this month, None if unlimited"
    )


class APIProviderInfo(BaseModel):
    """
    Информация об API провайдере генерации изображений.

    Используется в ImageGenerationStatusResponse.

    Attributes:
        provider: Название провайдера (OpenRouter/FLUX.2 Klein, etc.)
        supported_formats: Поддерживаемые форматы (PNG, JPG, etc.)
        max_resolution: Максимальное разрешение
        estimated_time_per_image: Ориентировочное время генерации
    """

    provider: str = Field(
        default="OpenRouter/FLUX.2 Klein", description="API provider name"
    )
    supported_formats: List[str] = Field(
        default=["PNG"], description="Supported image formats"
    )
    max_resolution: str = Field(default="1024x1024", description="Max resolution")
    estimated_time_per_image: str = Field(
        default="5-15 seconds", description="Estimated generation time"
    )


class ImageGenerationStatusResponse(BaseModel):
    """
    Полный статус системы генерации изображений.

    Используется в GET /api/v1/images/generation/status.

    Включает:
    - Статус сервиса (operational, degraded, down)
    - Статистику очереди генерации
    - Информацию о квоте пользователя
    - Информацию об API провайдере

    Attributes:
        status: Состояние сервиса
        queue_stats: Статистика очереди
        user_info: Информация о пользователе
        api_info: Информация об API провайдере
    """

    status: str = Field(
        default="operational",
        description="Service status: operational | degraded | down",
    )
    queue_stats: QueueStats
    user_info: UserGenerationInfo
    api_info: APIProviderInfo


class UserImageStatsResponse(BaseModel):
    """
    Статистика генерации изображений пользователя.

    Используется в GET /api/v1/images/user/stats.

    Подсчитывает:
    - Общее количество сгенерированных изображений
    - Общее количество найденных описаний
    - Разбивку по типам описаний

    Attributes:
        total_images_generated: Всего сгенерировано изображений
        total_descriptions_found: Всего найдено описаний
        images_by_type: Количество изображений по типам (LOCATION, CHARACTER, etc.)
    """

    total_images_generated: int = Field(
        ge=0, description="Total images generated by user"
    )
    total_descriptions_found: int = Field(
        ge=0, description="Total descriptions extracted from books"
    )
    images_by_type: Dict[str, int] = Field(
        default_factory=dict,
        description="Images count by description type (LOCATION, CHARACTER, ATMOSPHERE)",
    )


class ImageGenerationSuccessResponse(BaseModel):
    """
    Response для успешной генерации изображения.

    Используется в POST /api/v1/images/generate/description/{description_id}.

    Attributes:
        image_id: UUID сгенерированного изображения
        description_id: UUID описания
        image_url: URL изображения
        generation_time: Время генерации в секундах
        status: Статус генерации (completed)
        created_at: ISO timestamp создания
        message: Сообщение об успехе
    """

    image_id: UUID = Field(description="Generated image ID")
    description_id: UUID = Field(description="Source description ID")
    image_url: str = Field(description="URL of generated image")
    generation_time: float = Field(ge=0.0, description="Generation time in seconds")
    status: str = Field(default="completed", description="Generation status")
    created_at: str = Field(description="ISO timestamp of creation")
    message: str = Field(default="Image generated successfully")


# ============================================================================
# BATCH & DETAIL SCHEMAS (TD-P16-1b)
# ============================================================================


class DescriptionSummary(BaseModel):
    """Summary of description for image responses."""

    id: UUID
    type: str
    text: str
    content: str
    confidence_score: Optional[float] = None
    priority_score: Optional[float] = None


class ChapterSummary(BaseModel):
    """Summary of chapter for image responses."""

    id: UUID
    number: int
    title: str


class GeneratedImageSummary(BaseModel):
    """Single generated image in batch response."""

    description_id: UUID
    description_type: str
    image_url: Optional[str] = None
    generation_time: float


class BatchImageGenerationResponse(BaseModel):
    """Response for POST /images/generate/chapter/{chapter_id}."""

    chapter_id: UUID
    total_descriptions: int = Field(ge=0)
    processed: int = Field(ge=0)
    successful: int = Field(ge=0)
    failed: int = Field(ge=0)
    images: List[GeneratedImageSummary]
    message: str


class ImageDetailResponse(BaseModel):
    """Response for GET /images/description/{description_id}."""

    id: UUID
    image_url: str
    created_at: str
    generation_time_seconds: float = Field(ge=0)
    service_used: str = "imagen"
    status: str = "completed"
    is_moderated: bool = False
    view_count: int = Field(ge=0, default=0)
    download_count: int = Field(ge=0, default=0)
    description: DescriptionSummary
    chapter: ChapterSummary


class BookImageItem(BaseModel):
    """Single image item in book images list (simplified)."""

    id: UUID
    image_url: str
    created_at: str
    generation_time_seconds: float = Field(ge=0)
    description: DescriptionSummary
    chapter: ChapterSummary


class BookImagesResponse(BaseModel):
    """Response for GET /images/book/{book_id}."""

    book_id: UUID
    book_title: str
    images: List[BookImageItem]
    pagination: Dict[str, int]


class ImageDeleteResponse(BaseModel):
    """Response for DELETE /images/{image_id}."""

    message: str = "Image deleted successfully"


class ImageRegenerateResponse(BaseModel):
    """Response for POST /images/regenerate/{image_id}."""

    image_id: UUID
    description_id: UUID
    image_url: str
    generation_time: float = Field(ge=0)
    status: str = "regenerated"
    updated_at: Optional[str] = None
    message: str = "Image regenerated successfully"
    description: DescriptionSummary


class PerformanceStats(BaseModel):
    """Performance statistics for admin stats."""

    average_generation_time_seconds: Optional[float] = None
    current_queue_size: int = Field(ge=0)
    is_processing: bool


class SystemStatus(BaseModel):
    """System status for admin stats."""

    service_operational: bool = True
    api_provider: str = "OpenRouter/FLUX.2 Klein"
    supported_types: List[str]
    queue_backend: str = "celery_redis"


class AdminImageStatsResponse(BaseModel):
    """Response for GET /images/admin/stats."""

    total_images_generated: int = Field(ge=0)
    generation_by_type: Dict[str, int]
    performance: PerformanceStats
    system_status: SystemStatus
    celery_stats: Dict[str, int] = Field(default_factory=dict)


class AsyncGenerationQueueResponse(BaseModel):
    """Response for POST /images/generate/async/{description_id}."""

    task_id: str
    status: str = "queued"
    description_id: str
    message: str
    status_url: str


class AsyncBatchQueueResponse(BaseModel):
    """Response for POST /images/generate/async/chapter/{chapter_id}."""

    task_id: str
    status: str = "queued"
    chapter_id: str
    descriptions_count: int = Field(ge=0)
    total_descriptions: int = Field(ge=0)
    queued_for_processing: int = Field(ge=0)
    skipped_existing: int = Field(ge=0)
    status_url: str
    message: str


class AsyncBatchSkippedResponse(BaseModel):
    """Response when all descriptions already have images."""

    message: str
    chapter_id: str
    processed: int = 0
    skipped: int = Field(ge=0)


class TaskStatusResponse(BaseModel):
    """Response for GET /images/task/{task_id}."""

    task_id: str
    status: str
    ready: bool
    result: Optional[Dict] = None
    error: Optional[str] = None
    message: str


# ============================================================================
# EXPORTS
# ============================================================================

__all__ = [
    "QueueStats",
    "UserGenerationInfo",
    "APIProviderInfo",
    "ImageGenerationStatusResponse",
    "UserImageStatsResponse",
    "ImageGenerationSuccessResponse",
    "DescriptionSummary",
    "ChapterSummary",
    "GeneratedImageSummary",
    "BatchImageGenerationResponse",
    "ImageDetailResponse",
    "BookImageItem",
    "BookImagesResponse",
    "ImageDeleteResponse",
    "ImageRegenerateResponse",
    "PerformanceStats",
    "SystemStatus",
    "AdminImageStatsResponse",
    "AsyncGenerationQueueResponse",
    "AsyncBatchQueueResponse",
    "AsyncBatchSkippedResponse",
    "TaskStatusResponse",
]
