"""
A/B comparison tests: GLiNER2 NER vs LLM baseline.

Tests entity recall and confidence threshold calibration using
fixture data exported from production DB.

Requirements:
- NER-04: A/B test recall >= 80% vs LLM baseline
- NER-05: Confidence threshold calibrated via sweep 0.25-0.60

Fixtures generated by: scripts/export_ner_ab_data.py
"""

import json
import logging
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

logger = logging.getLogger(__name__)


# ============================================================================
# Fixture directory and book discovery
# ============================================================================

FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "ner_ab_data"


def get_available_books() -> list[str]:
    """
    Scan fixture directory for valid book pairs.

    A valid book has both {name}_chapters.json and {name}_baseline.json.
    Returns list of book name stems (e.g., ["book1", "book2"]).
    """
    if not FIXTURE_DIR.exists():
        return []

    chapters_files = set()
    baseline_files = set()

    for f in FIXTURE_DIR.iterdir():
        if f.suffix == ".json":
            if f.name.endswith("_chapters.json"):
                stem = f.name.replace("_chapters.json", "")
                chapters_files.add(stem)
            elif f.name.endswith("_baseline.json"):
                stem = f.name.replace("_baseline.json", "")
                baseline_files.add(stem)

    # Only books that have both files
    valid = sorted(chapters_files & baseline_files)
    return valid


available_books = get_available_books()

skip_no_fixtures = pytest.mark.skipif(
    len(available_books) < 1,
    reason="No fixture data. Run: uv run python scripts/export_ner_ab_data.py --auto-select 5",
)


# ============================================================================
# Utility functions (D-16: matching logic from ConsistencyManager)
# ============================================================================


def fuzzy_match(name1: str, name2: str) -> bool:
    """
    Fuzzy match two entity names using the same logic as ConsistencyManager.

    D-16 matching criteria:
    1. Exact casefold equality
    2. SequenceMatcher ratio > 0.75
    3. Token overlap >= 0.5
    """
    n1, n2 = name1.casefold(), name2.casefold()

    # 1. Exact match
    if n1 == n2:
        return True

    # 2. Sequence similarity
    if SequenceMatcher(None, n1, n2).ratio() > 0.75:
        return True

    # 3. Token overlap
    tokens1 = set(n1.split())
    tokens2 = set(n2.split())
    overlap = tokens1 & tokens2
    if overlap and len(overlap) / max(len(tokens1), len(tokens2)) >= 0.5:
        return True

    return False


def calculate_recall(ner_names: list[str], baseline_names: list[str]) -> float:
    """
    Calculate recall: fraction of baseline entities found by NER.

    Each baseline entity is matched against all NER entities using fuzzy_match.
    """
    if not baseline_names:
        return 1.0

    matched = 0
    for baseline_name in baseline_names:
        for ner_name in ner_names:
            if fuzzy_match(baseline_name, ner_name):
                matched += 1
                break

    return matched / len(baseline_names)


def calculate_precision(ner_names: list[str], baseline_names: list[str]) -> float:
    """
    Calculate precision: fraction of NER entities that have a match in baseline.
    """
    if not ner_names:
        return 1.0

    matched = 0
    for ner_name in ner_names:
        for baseline_name in baseline_names:
            if fuzzy_match(ner_name, baseline_name):
                matched += 1
                break

    return matched / len(ner_names)


def load_book_fixtures(book_name: str) -> tuple[dict, dict]:
    """Load chapters and baseline JSON fixtures for a book."""
    chapters_path = FIXTURE_DIR / f"{book_name}_chapters.json"
    baseline_path = FIXTURE_DIR / f"{book_name}_baseline.json"

    with open(chapters_path, encoding="utf-8") as f:
        chapters_data = json.load(f)
    with open(baseline_path, encoding="utf-8") as f:
        baseline_data = json.load(f)

    return chapters_data, baseline_data


def _create_ner_service_with_mock() -> Any:
    """
    Create NERService with mocked model loading for test environments.

    The actual GLiNER2 model (~500MB) may not be available in CI.
    When fixtures exist but model is not available, tests will still
    attempt to run with the real model. If import fails, test is skipped.
    """
    try:
        from app.services.ner_service import NERService

        service = NERService()
        return service
    except ImportError:
        pytest.skip("NERService not available")
        return None  # unreachable, but makes type checker happy


# ============================================================================
# A/B Recall Test (NER-04)
# ============================================================================


@skip_no_fixtures
@pytest.mark.parametrize("book_name", available_books or ["placeholder"])
def test_ner_recall_vs_llm_baseline(book_name: str) -> None:
    """
    A/B test: GLiNER2 entity recall vs LLM baseline.

    For each book:
    1. Load chapter text + LLM baseline entities from fixtures
    2. Run NERService.extract_chapter() on each chapter
    3. Collect all NER entity names
    4. Calculate recall vs baseline using fuzzy matching (D-16)
    5. Assert recall >= 0.80 (NER-04)
    """
    if book_name == "placeholder":
        pytest.skip("No fixture data available")

    chapters_data, baseline_data = load_book_fixtures(book_name)

    # Create NER service
    service = _create_ner_service_with_mock()

    # Extract entities from each chapter
    ner_entity_names: set[str] = set()

    for chapter in chapters_data["chapters"]:
        result = service.extract_chapter(chapter["content"])
        for entity in result.entities:
            ner_entity_names.add(entity.name)

    # Baseline entity names
    baseline_names = [e["name"] for e in baseline_data["entities"]]

    # Calculate recall
    recall = calculate_recall(list(ner_entity_names), baseline_names)

    # Diagnostic output
    print(f"\n{'='*60}")
    print(f"Book: {chapters_data['book_title']}")
    print(f"Chapters: {len(chapters_data['chapters'])}")
    print(f"NER entities: {len(ner_entity_names)}")
    print(f"Baseline entities: {len(baseline_names)}")
    print(f"Recall: {recall:.2%}")

    # Show unmatched baseline entities for debugging
    unmatched = []
    for baseline_name in baseline_names:
        if not any(fuzzy_match(baseline_name, n) for n in ner_entity_names):
            unmatched.append(baseline_name)
    if unmatched:
        print(f"Unmatched baseline ({len(unmatched)}): {unmatched[:20]}")
    print(f"{'='*60}")

    assert recall >= 0.80, (
        f"Book '{chapters_data['book_title']}': "
        f"recall {recall:.2%} < 80% "
        f"(NER: {len(ner_entity_names)}, baseline: {len(baseline_names)})"
    )


# ============================================================================
# Threshold Sweep Test (NER-05)
# ============================================================================

SWEEP_THRESHOLDS = [0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]


@skip_no_fixtures
def test_confidence_threshold_sweep() -> None:
    """
    Sweep confidence thresholds 0.25-0.60 to find optimal value.

    For each book x threshold combination:
    1. Chunk text with TextChunker
    2. Extract entities with specific threshold
    3. Deduplicate and adapt
    4. Calculate recall, precision, F1

    Optimal threshold: recall >= 0.80 with maximum F1.
    """
    from app.services.ner_service import (
        NERAdapter,
        NERService,
        TextChunker,
        deduplicate_overlap_entities,
    )

    service = NERService()
    service._ensure_loaded()

    # Aggregate results: threshold -> list of (recall, precision, f1)
    results: dict[float, list[dict[str, float]]] = {t: [] for t in SWEEP_THRESHOLDS}

    for book_name in available_books:
        chapters_data, baseline_data = load_book_fixtures(book_name)
        baseline_names = [e["name"] for e in baseline_data["entities"]]

        for threshold in SWEEP_THRESHOLDS:
            ner_entity_names: set[str] = set()

            for chapter in chapters_data["chapters"]:
                text = chapter["content"]

                # 1. Chunk
                chunks = TextChunker.chunk_text(
                    text, service._tokenizer, max_tokens=384, overlap_sentences=2
                )

                # 2. Extract with specific threshold
                all_entities: list[dict[str, Any]] = []
                chunk_offsets: list[tuple[int, int]] = []

                for chunk in chunks:
                    raw = service.extract_entities(
                        chunk.text,
                        ["person", "location", "artifact", "organization"],
                        threshold=threshold,
                    )
                    # Adjust offsets to chapter-level
                    for ent in raw:
                        ent["start"] += chunk.start_offset
                        ent["end"] += chunk.start_offset
                    all_entities.extend(raw)
                    chunk_offsets.append((chunk.start_offset, chunk.end_offset))

                # 3. Dedup + adapt
                deduped = deduplicate_overlap_entities(all_entities)
                chapter_result = NERAdapter.adapt_to_chapter_result(
                    deduped, chunk_offsets
                )

                for entity in chapter_result.entities:
                    ner_entity_names.add(entity.name)

            # 4. Calculate metrics
            ner_list = list(ner_entity_names)
            recall = calculate_recall(ner_list, baseline_names)
            precision = calculate_precision(ner_list, baseline_names)
            f1 = (
                2 * precision * recall / (precision + recall)
                if (precision + recall) > 0
                else 0.0
            )

            results[threshold].append(
                {"recall": recall, "precision": precision, "f1": f1}
            )

    # Aggregate: average across all books
    print(f"\n{'='*70}")
    print(
        f"{'Threshold':>10} | {'Avg Recall':>10} | {'Avg Precision':>13} | {'Avg F1':>8}"
    )
    print(f"{'-'*10}-+-{'-'*10}-+-{'-'*13}-+-{'-'*8}")

    best_threshold: float | None = None
    best_f1: float = 0.0

    for threshold in SWEEP_THRESHOLDS:
        book_results = results[threshold]
        if not book_results:
            continue

        avg_recall = sum(r["recall"] for r in book_results) / len(book_results)
        avg_precision = sum(r["precision"] for r in book_results) / len(book_results)
        avg_f1 = sum(r["f1"] for r in book_results) / len(book_results)

        marker = ""
        if avg_recall >= 0.80 and avg_f1 > best_f1:
            best_f1 = avg_f1
            best_threshold = threshold
            marker = " <-- best"

        print(
            f"{threshold:>10.2f} | {avg_recall:>10.2%} | {avg_precision:>13.2%} | {avg_f1:>8.3f}{marker}"
        )

    print(f"{'='*70}")

    if best_threshold is not None:
        print(f"\nOptimal threshold: {best_threshold} (F1={best_f1:.3f})")
    else:
        print("\nWARNING: No threshold achieves recall >= 80%")

    # Assertions
    assert best_threshold is not None, (
        "No threshold in range [0.25, 0.60] achieves recall >= 80%. "
        "Review NER model quality or adjust threshold range."
    )
    assert (
        0.25 <= best_threshold <= 0.60
    ), f"Optimal threshold {best_threshold} outside expected range [0.25, 0.60]"
