"""add_universal_entities_and_graph

Revision ID: 4311e80fcf3d
Revises: 2026_01_20_0001
Create Date: 2026-01-20 19:23:17.905615+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4311e80fcf3d'
down_revision: Union[str, None] = '2026_01_20_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visual_summary', sa.Text(), nullable=True),
    sa.Column('master_portrait_url', sa.String(length=1000), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_book_id'), 'entities', ['book_id'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('relationship_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relationships_id'), 'entity_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_id'), 'entity_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_id'), 'entity_relationships', ['target_id'], unique=False)
    op.alter_column('books', 'is_processing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'descriptions_extracted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_chapters_book_chapter_unique', table_name='chapters')
    op.drop_index('idx_chapters_parsed', table_name='chapters', postgresql_where='(is_description_parsed = true)')
    op.alter_column('descriptions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('descriptions', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('descriptions', 'is_suitable_for_generation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('descriptions', 'priority_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('descriptions', 'image_generated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('descriptions', 'generation_requested',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_descriptions_chapter_position', table_name='descriptions')
    op.drop_index('ix_descriptions_priority_score', table_name='descriptions')
    op.drop_constraint('descriptions_chapter_id_fkey', 'descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'descriptions', 'chapters', ['chapter_id'], ['id'])
    op.alter_column('feature_flags', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_comment='Whether the flag is enabled',
               existing_nullable=False)
    op.alter_column('feature_flags', 'default_value',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_comment='Default value (fallback if flag not found)',
               existing_nullable=False)
    op.alter_column('generated_images', 'description_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_generated_images_chapter_id', 'generated_images', type_='foreignkey')
    op.drop_constraint('generated_images_description_id_fkey', 'generated_images', type_='foreignkey')
    op.create_foreign_key(None, 'generated_images', 'descriptions', ['description_id'], ['id'])
    op.create_foreign_key(None, 'generated_images', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('generated_images', 'description_text')
    op.drop_column('generated_images', 'description_type')
    op.alter_column('push_subscriptions', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the subscription',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to user who owns this subscription',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Push service endpoint URL (unique per device)',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'p256dh_key',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Client P-256 ECDH public key for encryption',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'auth_key',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Authentication secret for the subscription',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Whether the subscription is still valid',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the subscription was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('push_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the subscription was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reading_goals', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор цели',
               existing_nullable=False)
    op.alter_column('reading_goals', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID пользователя (внешний ключ)',
               existing_nullable=False)
    op.alter_column('reading_goals', 'goal_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Тип цели: 'books', 'minutes', 'pages', 'streak'",
               existing_nullable=False)
    op.alter_column('reading_goals', 'goal_period',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Период цели: 'daily', 'weekly', 'monthly', 'yearly'",
               existing_nullable=False)
    op.alter_column('reading_goals', 'target_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Целевое значение (N книг, N минут, N страниц, N дней)',
               existing_nullable=False)
    op.alter_column('reading_goals', 'current_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment=None,
               existing_comment='Текущее значение (прогресс)',
               existing_nullable=False)
    op.alter_column('reading_goals', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата начала периода цели',
               existing_nullable=False)
    op.alter_column('reading_goals', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата окончания периода цели',
               existing_nullable=False)
    op.alter_column('reading_goals', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Активна ли цель в данный момент',
               existing_nullable=False)
    op.alter_column('reading_goals', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment=None,
               existing_comment='Выполнена ли цель',
               existing_nullable=False)
    op.alter_column('reading_goals', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда была выполнена цель',
               existing_nullable=True)
    op.alter_column('reading_goals', 'last_progress_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда последний раз обновлялся прогресс',
               existing_nullable=True)
    op.alter_column('reading_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата создания цели',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reading_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата последнего обновления',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_reading_progress_user_book', table_name='reading_progress')
    op.alter_column('users', 'longest_streak_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'longest_streak_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index('idx_reading_progress_user_book', 'reading_progress', ['user_id', 'book_id'], unique=True)
    op.alter_column('reading_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата последнего обновления',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reading_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания цели',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reading_goals', 'last_progress_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда последний раз обновлялся прогресс',
               existing_nullable=True)
    op.alter_column('reading_goals', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда была выполнена цель',
               existing_nullable=True)
    op.alter_column('reading_goals', 'is_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment='Выполнена ли цель',
               existing_nullable=False)
    op.alter_column('reading_goals', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='Активна ли цель в данный момент',
               existing_nullable=False)
    op.alter_column('reading_goals', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата окончания периода цели',
               existing_nullable=False)
    op.alter_column('reading_goals', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата начала периода цели',
               existing_nullable=False)
    op.alter_column('reading_goals', 'current_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               comment='Текущее значение (прогресс)',
               existing_nullable=False)
    op.alter_column('reading_goals', 'target_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Целевое значение (N книг, N минут, N страниц, N дней)',
               existing_nullable=False)
    op.alter_column('reading_goals', 'goal_period',
               existing_type=sa.VARCHAR(length=20),
               comment="Период цели: 'daily', 'weekly', 'monthly', 'yearly'",
               existing_nullable=False)
    op.alter_column('reading_goals', 'goal_type',
               existing_type=sa.VARCHAR(length=20),
               comment="Тип цели: 'books', 'minutes', 'pages', 'streak'",
               existing_nullable=False)
    op.alter_column('reading_goals', 'user_id',
               existing_type=sa.UUID(),
               comment='ID пользователя (внешний ключ)',
               existing_nullable=False)
    op.alter_column('reading_goals', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор цели',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the subscription was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('push_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the subscription was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('push_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='Whether the subscription is still valid',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'auth_key',
               existing_type=sa.VARCHAR(length=50),
               comment='Authentication secret for the subscription',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'p256dh_key',
               existing_type=sa.VARCHAR(length=200),
               comment='Client P-256 ECDH public key for encryption',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'endpoint',
               existing_type=sa.VARCHAR(length=500),
               comment='Push service endpoint URL (unique per device)',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'user_id',
               existing_type=sa.UUID(),
               comment='Foreign key to user who owns this subscription',
               existing_nullable=False)
    op.alter_column('push_subscriptions', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the subscription',
               existing_nullable=False)
    op.add_column('generated_images', sa.Column('description_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('generated_images', sa.Column('description_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.drop_constraint(None, 'generated_images', type_='foreignkey')
    op.create_foreign_key('generated_images_description_id_fkey', 'generated_images', 'descriptions', ['description_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_generated_images_chapter_id', 'generated_images', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('generated_images', 'description_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('feature_flags', 'default_value',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Default value (fallback if flag not found)',
               existing_nullable=False)
    op.alter_column('feature_flags', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Whether the flag is enabled',
               existing_nullable=False)
    op.drop_constraint(None, 'descriptions', type_='foreignkey')
    op.create_foreign_key('descriptions_chapter_id_fkey', 'descriptions', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_descriptions_priority_score', 'descriptions', ['priority_score'], unique=False)
    op.create_index('idx_descriptions_chapter_position', 'descriptions', ['chapter_id', 'position_in_chapter'], unique=False)
    op.alter_column('descriptions', 'generation_requested',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('descriptions', 'image_generated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('descriptions', 'priority_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.alter_column('descriptions', 'is_suitable_for_generation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('descriptions', 'word_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('descriptions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False)
    op.create_index('idx_chapters_parsed', 'chapters', ['book_id', 'chapter_number'], unique=False, postgresql_where='(is_description_parsed = true)')
    op.create_index('idx_chapters_book_chapter_unique', 'chapters', ['book_id', 'chapter_number'], unique=True)
    op.alter_column('books', 'descriptions_extracted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('books', 'is_processing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_entity_relationships_target_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_book_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
